editar_podcast:
  path: /editar-podcast/{id}
  controller: App\Controller\PostsController::editar

eliminar_podcast:
  path: /borrar-podcast/{id}
  controller: App\Controller\PostsController::delete

editarPodcast:
  path: /editar-podcast
  controller: App\Controller\PostsController::editarPodcast
